# Generated by Django 3.0.5 on 2020-05-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('comment_number', models.AutoField(db_column='Comment#', primary_key=True, serialize=False)),
                ('com_content', models.CharField(max_length=45)),
                ('com_parent', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField()),
                ('com_user_number', models.IntegerField(db_column='com_user#')),
            ],
            options={
                'db_table': 'comment_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MusicDataGet',
            fields=[
                ('MDG_music_number', models.AutoField(db_column='music#', primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=50)),
                ('song', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'music_data_get',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MusicDataIntegrated',
            fields=[
                ('in_music_number', models.AutoField(db_column='in_music#', primary_key=True, serialize=False)),
                ('in_artist', models.CharField(max_length=50)),
                ('song', models.CharField(max_length=100)),
                ('in_album', models.CharField(max_length=100)),
                ('in_site_code', models.CharField(max_length=1, unique=True)),
                ('in_genre', models.CharField(blank=True, max_length=45, null=True)),
                ('in_list_no', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'music_data_integrated',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MusicDataSend',
            fields=[
                ('MDS_music_number', models.AutoField(db_column='music#', primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=50)),
                ('song', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'music_data_send',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostFileTable',
            fields=[
                ('postfi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('postfi_originname', models.CharField(blank=True, max_length=45, null=True)),
                ('postfi_filename', models.CharField(blank=True, max_length=45, null=True)),
                ('postfi_download', models.IntegerField(blank=True, null=True)),
                ('postfi_filesize', models.IntegerField(blank=True, null=True)),
                ('postfi_type', models.CharField(blank=True, max_length=45, null=True)),
                ('postfi_datetime', models.DateTimeField(blank=True, null=True)),
                ('postfi_p', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'post_file_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareTable',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_pid', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('hits', models.IntegerField()),
                ('reg_date', models.DateTimeField()),
                ('board_number', models.IntegerField()),
            ],
            options={
                'db_table': 'share_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_number', models.AutoField(db_column='user#', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('rank', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=200)),
                ('userprofile', models.CharField(max_length=225)),
                ('regtime', models.DateTimeField()),
                ('is_admin', models.IntegerField()),
                ('user_email', models.CharField(db_column='user_Email', max_length=50)),
                ('user_like_genre', models.CharField(blank=True, db_column='User_like_genre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendTable',
            fields=[
                ('re_in_music_number', models.OneToOneField(db_column='Re_in_music#', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.MusicDataIntegrated')),
                ('re_from_user_number', models.IntegerField(db_column='Re_from_user#', unique=True)),
                ('re_list_no', models.IntegerField(db_column='Re_list_no')),
            ],
            options={
                'db_table': 'recommend_table',
                'managed': False,
            },
        ),
    ]
