# Generated by Django 3.0.5 on 2020-05-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200505_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicdataget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='musicdataintegrated',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='musicdatasend',
            options={'managed': False},
        ),
    ]
