# Generated by Django 3.0.5 on 2020-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200508_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_writer', models.CharField(max_length=100)),
                ('com_password', models.IntegerField()),
                ('com_date', models.DateTimeField(auto_now_add=True)),
                ('com_contents', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-com_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mdg',
            fields=[
                ('user_num', models.IntegerField(db_column='User_num', primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=50)),
                ('song', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=1)),
                ('genre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'MDG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdIntegratedM',
            fields=[
                ('in_artist', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('in_song', models.CharField(max_length=100)),
                ('in_album', models.CharField(max_length=100)),
                ('in_genre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'MD_integrated_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=45)),
                ('post_contents', models.TextField(blank=True, help_text='Post Contents')),
                ('post_hit', models.IntegerField()),
                ('post_like', models.IntegerField()),
                ('post_file', models.TextField(blank=True, null=True)),
                ('table_num', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['-post_date'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CommentTable',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='MusicDataGet',
        ),
        migrations.DeleteModel(
            name='MusicDataSend',
        ),
        migrations.DeleteModel(
            name='PostFileTable',
        ),
        migrations.RemoveField(
            model_name='recommendtable',
            name='re_in_music_number',
        ),
        migrations.DeleteModel(
            name='ShareTable',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='MusicDataIntegrated',
        ),
        migrations.DeleteModel(
            name='RecommendTable',
        ),
    ]
