# Generated by Django 3.0.5 on 2020-05-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200526_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False, 'ordering': ['-post_id']},
        ),
    ]
